

'ExternalFile.dlg
#Define IDD_DLGEXTERNALFILE			    	4100
#Define IDC_BTNCOMMANDBROWSE				4106
#Define IDC_EDTCOMMAND						4105
#Define IDC_EDTFILETYPE						4104
#Define IDC_LSTFILETYPE						4101
#Define IDC_BTNADDFILETYPE					4102
#Define IDC_BTNDELETEFILETYPE				4103
