
@echo off

setlocal enabledelayedexpansion

if /i "%compilin_bname%"=="FbEdit" (
    echo *** reading SVN Revision ***

	set IncFile=".\Inc\SVNVersion.bi"
    :: line feed hack
	set LF= ^


	:: space required, two empty lines required
	set IncHead=!LF!' This file is generated by script, dont edit!LF!

	echo !IncHead! > !IncFile!
	echo #define SVN_REV "$WCREV$$WCMODS? - modified:$" >> !IncFile!
    SubWCRev.exe "%CD%\..\.." !IncFile! !IncFile!  || goto :ERR_Exit
) else (
    echo skipped
)



:OK_Exit
exit /b 0


:ERR_Exit
echo *** ERROR - Reading SVN Revision ***
echo !IncHead! > !IncFile!
echo #define SVN_REV "undefined" >> !IncFile!
exit /b 0

