"%FBHome%\FBC.EXE" %BFLAGS_MAIN%  "Src\FbEdit.bas"          ^
                                  "Res\FbEdit.rc"           ^
                                  "Src\Environment.o"       ^
                                  "Src\Language.o"          ^
                                  "Src\IniFile.o"           ^
                                  "Src\Project.o"           ^
                                  "Src\ZStringHandling.o"   ^
                                  "Src\GUIHandling.o"       ^
                                  "Src\SpecHandling.o"      ^
                                  "Src\CoTxEd.o"            ^
                                  "Src\Goto.o"              ^
                                  "Src\EditorOpt.o"         ^
                                  "Src\TabTool.o"           ^
                                  "Src\Make.o"              ^
                                  "Src\GenericOpt.o"        ^
                                  "Src\CodeComplete.o"      ^
                                  "Src\FileIO.o"            ^
                                  "Src\Misc.o"              ^
                                  "Src\Property.o"          ^
                                  "Src\Splash.o"            ^
                                  "Src\CBH_Dialog.o"        ^
                                  "Src\Find.o"              ^
                                  "Src\HexFind.o"           ^
                                  "Src\LineQueue.o"         ^
                                  "Src\Toolbar.o"           ^
                                  "Src\ResEd.o"             ^
                                  "Src\ResEdOpt.o"          ^
                                  "Src\About.o"             ^
                                  "Src\BlockInsert.o"       ^
                                  "Src\ZStringHandling2.o"  ^
                                  "Src\CreateTemplate.o"    ^
                                  "Src\Export.o"            ^
                                  "Src\Addins.o"            ^
                                  "Src\DebugOpt.o"          ^
                                  "Src\CustomFilter.o"      ^
                                  "Src\HexEd.o"             ^
                                  "Src\FileMonitor.o"       ^
                                  "Src\Statusbar.o"         ^
                                  -x "Build\FbEdit.exe"