
' Toolbar bitmap
#Define IDB_TBRBMP							100

' ToolBar

Sub DoToolbar(ByVal hTbr As HWND,ByVal hInst As HINSTANCE)
	Dim tbab As TBADDBITMAP
	Dim tbrbtn36 As TBBUTTON=(0,0,TBSTATE_ENABLED,TBSTYLE_SEP,{0,0},0)
	Dim tbrbtn35 As TBBUTTON=(15,IDM_MAKE_GO,TBSTATE_ENABLED,TBSTYLE_BUTTON,{0,0},0)
	Dim tbrbtn34 As TBBUTTON=(14,IDM_MAKE_RUN,TBSTATE_ENABLED,TBSTYLE_BUTTON,{0,0},0)
	Dim tbrbtn33 As TBBUTTON=(12,IDM_MAKE_COMPILE,TBSTATE_ENABLED,TBSTYLE_BUTTON,{0,0},0)
	Dim tbrbtn32 As TBBUTTON=(0,0,TBSTATE_ENABLED,TBSTYLE_SEP,{0,0},0)
	Dim tbrbtn31 As TBBUTTON=(23,IDM_VIEW_PROPERTY,TBSTATE_ENABLED,TBSTYLE_BUTTON Or TBSTYLE_CHECK,{0,0},0)
	Dim tbrbtn30 As TBBUTTON=(22,IDM_VIEW_PROJECT,TBSTATE_ENABLED,TBSTYLE_BUTTON Or TBSTYLE_CHECK,{0,0},0)
	Dim tbrbtn29 As TBBUTTON=(29,IDM_VIEW_IMMEDIATE,TBSTATE_ENABLED,TBSTYLE_BUTTON Or TBSTYLE_CHECK,{0,0},0)
	Dim tbrbtn28 As TBBUTTON=(21,IDM_VIEW_OUTPUT,TBSTATE_ENABLED,TBSTYLE_BUTTON Or TBSTYLE_CHECK,{0,0},0)
	Dim tbrbtn27 As TBBUTTON=(0,0,TBSTATE_ENABLED,TBSTYLE_SEP,{0,0},0)
	Dim tbrbtn26 As TBBUTTON=(27,IDM_EDIT_BLOCKUNCOMMENT,TBSTATE_ENABLED,TBSTYLE_BUTTON,{0,0},0)
	Dim tbrbtn25 As TBBUTTON=(26,IDM_EDIT_BLOCKCOMMENT,TBSTATE_ENABLED,TBSTYLE_BUTTON,{0,0},0)
	Dim tbrbtn24 As TBBUTTON=(24,IDM_EDIT_BLOCKOUTDENT,TBSTATE_ENABLED,TBSTYLE_BUTTON,{0,0},0)
	Dim tbrbtn23 As TBBUTTON=(25,IDM_EDIT_BLOCKINDENT,TBSTATE_ENABLED,TBSTYLE_BUTTON,{0,0},0)
	Dim tbrbtn22 As TBBUTTON=(0,0,TBSTATE_ENABLED,TBSTYLE_SEP,{0,0},0)
	Dim tbrbtn21 As TBBUTTON=(19,IDM_EDIT_BOOKMARKDELETE,TBSTATE_ENABLED,TBSTYLE_BUTTON,{0,0},0)
	Dim tbrbtn20 As TBBUTTON=(17,IDM_EDIT_BOOKMARKNEXT,TBSTATE_ENABLED,TBSTYLE_BUTTON,{0,0},0)
	Dim tbrbtn19 As TBBUTTON=(18,IDM_EDIT_BOOKMARKPREVIOUS,TBSTATE_ENABLED,TBSTYLE_BUTTON,{0,0},0)
	Dim tbrbtn18 As TBBUTTON=(16,IDM_EDIT_BOOKMARKTOGGLE,TBSTATE_ENABLED,TBSTYLE_BUTTON,{0,0},0)
	Dim tbrbtn17 As TBBUTTON=(0,0,TBSTATE_ENABLED,TBSTYLE_SEP,{0,0},0)
	Dim tbrbtn16 As TBBUTTON=(10,IDM_EDIT_REPLACE,TBSTATE_ENABLED,TBSTYLE_BUTTON,{0,0},0)
	Dim tbrbtn15 As TBBUTTON=(9,IDM_EDIT_FIND,TBSTATE_ENABLED,TBSTYLE_BUTTON,{0,0},0)
	Dim tbrbtn14 As TBBUTTON=(0,0,TBSTATE_ENABLED,TBSTYLE_SEP,{0,0},0)
	Dim tbrbtn13 As TBBUTTON=(4,IDM_EDIT_REDO,TBSTATE_ENABLED,TBSTYLE_BUTTON,{0,0},0)
	Dim tbrbtn12 As TBBUTTON=(3,IDM_EDIT_UNDO,TBSTATE_ENABLED,TBSTYLE_BUTTON,{0,0},0)
	Dim tbrbtn11 As TBBUTTON=(0,0,TBSTATE_ENABLED,TBSTYLE_SEP,{0,0},0)
	Dim tbrbtn10 As TBBUTTON=(5,IDM_EDIT_DELETE,TBSTATE_ENABLED,TBSTYLE_BUTTON,{0,0},0)
	Dim tbrbtn9 As TBBUTTON=(2,IDM_EDIT_PASTE,TBSTATE_ENABLED,TBSTYLE_BUTTON,{0,0},0)
	Dim tbrbtn8 As TBBUTTON=(1,IDM_EDIT_COPY,TBSTATE_ENABLED,TBSTYLE_BUTTON,{0,0},0)
	Dim tbrbtn7 As TBBUTTON=(0,IDM_EDIT_CUT,TBSTATE_ENABLED,TBSTYLE_BUTTON,{0,0},0)
	Dim tbrbtn6 As TBBUTTON=(0,0,TBSTATE_ENABLED,TBSTYLE_SEP,{0,0},0)
	Dim tbrbtn5 As TBBUTTON=(11,IDM_FILE_SAVEALL,TBSTATE_ENABLED,TBSTYLE_BUTTON,{0,0},0)
	Dim tbrbtn4 As TBBUTTON=(8,IDM_FILE_SAVE,TBSTATE_ENABLED,TBSTYLE_BUTTON,{0,0},0)
	Dim tbrbtn3 As TBBUTTON=(7,IDM_FILE_OPEN,TBSTATE_ENABLED,TBSTYLE_BUTTON,{0,0},0)
	Dim tbrbtn2 As TBBUTTON=(6,IDM_FILE_NEW,TBSTATE_ENABLED,TBSTYLE_BUTTON,{0,0},0)
	Dim tbrbtn1 As TBBUTTON=(0,0,TBSTATE_ENABLED,TBSTYLE_SEP,{0,0},0)

	'Set toolbar struct size
	SendMessage(hTbr,TB_BUTTONSTRUCTSIZE,SizeOf(TBBUTTON),0)
	'Set toolbar bitmap
	tbab.hInst=hInst
	tbab.nID=IDB_TBRBMP
	SendMessage(hTbr,TB_ADDBITMAP,30,Cast(LPARAM,@tbab))
	'Set toolbar buttons
	SendMessage(hTbr,TB_ADDBUTTONS,36,Cast(LPARAM,@tbrbtn1))

End Sub
